#!/bin/bash

## Created By Aditya Shakya

MENU="$(rofi -sep "|" -dmenu -i -p 'System' -location 3 -xoffset -10 -yoffset 36 -width 8 -line-padding 4 -padding 20 -lines 4 -theme-str '* { scrollbar: false; }' <<< "> Lock|> Logout|> Reboot|> Shutdown")"
            case "$MENU" in
                #*Lock) i3lock-fancy ;;
                #*Logout) openbox --exit;;
                *Reboot) systemctl reboot ;;
                *Shutdown) systemctl -i poweroff
            esac
